POST http://localhost:7071/api/sorting-fast
Content-Type: application/json

[
  5,
  3,
  4,
  1,
  2
]

###

POST http://localhost:7071/api/sorting-slow
Content-Type: application/json

[
  5,
  3,
  4,
  1,
  2
]

###

POST https://sorting-function-java-15052023.azurewebsites.net/api/sorting-fast
Content-Type: application/json

[
  5,
  3,
  4,
  1,
  2
]

###

POST https://sorting-function-java-15052023.azurewebsites.net/api/sorting-slow
Content-Type: application/json

[
  5,
  3,
  4,
  1,
  2
]
